services:
  bunbot:
    build: .
    container_name: 'bunbot'
    volumes:
      - ./:/app
    environment:
      - CLUSTER_ID=0
  bunbot1:
    container_name: 'bunbot1'
    extends:
      service: bunbot
    environment:
      - CLUSTER_ID=1
